spring:
  rabbitmq:
    host: 192.168.163.129
    username: guest
    password: guest
    publisher-confirm-type: correlated  # 新版本
    publisher-returns: true # 开启Return机制
    listener:
      simple:
        acknowledge-mode: manual  # 开启手动Ack
        prefetch: 10