version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:7.8.1
    restart: always
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  kibana:
    image: kibana:7.0.1
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://123.60.5.25:9200"]
      - I18N_LOCALE="zh-CN"
    ports:
      - 5601:5601
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        
networks:
  default:
    external:
      name: aaaa_default
